### ISSUE TITLE
Questions of installing f110 base system

### ISSUE THREAD

**Issue by yhslc** [wueestry/f110_mpcc#2]
Can you provide a link to install f110 base system? I don't know which project on GitHub to use.

**Comment by wueestry** [comment]
Sadly I don't have access to the complete base system used for this project anymore, but was based on the work done in [f1tenth base system](https://github.com/f1tenth/f1tenth_system) with some marginal changes.
It can easily be adjusted for any base system by changing the ROS messages to the correct addresses.
